var classnet_1_1minecraftforge_1_1client_1_1event_1_1_draw_highlight_event =
[
    [ "HighlightBlock", "classnet_1_1minecraftforge_1_1client_1_1event_1_1_draw_highlight_event_1_1_highlight_block.html", "classnet_1_1minecraftforge_1_1client_1_1event_1_1_draw_highlight_event_1_1_highlight_block" ],
    [ "HighlightEntity", "classnet_1_1minecraftforge_1_1client_1_1event_1_1_draw_highlight_event_1_1_highlight_entity.html", "classnet_1_1minecraftforge_1_1client_1_1event_1_1_draw_highlight_event_1_1_highlight_entity" ]
];